services:
  web:
    build:
      context: .  # Build context is the root directory
    ports:
      - "5000:5000"  # Expose port 5000 on the host
    volumes:
      - .:/app  # Mount the project directory into the container for development
    environment:
      - FLASK_ENV=development  # Set Flask environment to development
    depends_on:
      - db  # Ensure the database service starts first

  db:
    image: mysql:8.0  # Use the MySQL 8.0 image
    ports:
      - "3306:3306"  # Expose port 3306 for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql 

volumes:
  db_data:  # Define a named volume for MySQL data persistence
